'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Assignment3_MVC

    Partial Public Class Agri_Products
        Public Property Product_ID As Integer
        Public Property Product_Name As String
    
        Public Overridable Property Fruits As ICollection(Of Fruit) = New HashSet(Of Fruit)
        Public Overridable Property Vegetables As ICollection(Of Vegetable) = New HashSet(Of Vegetable)
    
    End Class

End Namespace
