'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace Assignment3_MVC

    Partial Public Class Agriculture_DatabaseEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=Agriculture_DatabaseEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property Agri_Products() As DbSet(Of Agri_Products)
        Public Overridable Property Apples() As DbSet(Of Apple)
        Public Overridable Property Apricots() As DbSet(Of Apricot)
        Public Overridable Property Blueberries() As DbSet(Of Blueberry)
        Public Overridable Property Fruits() As DbSet(Of Fruit)
        Public Overridable Property Mushrooms() As DbSet(Of Mushroom)
        Public Overridable Property Potatoes() As DbSet(Of Potato)
        Public Overridable Property Tomatoes() As DbSet(Of Tomato)
        Public Overridable Property Vegetables() As DbSet(Of Vegetable)
    
    End Class

End Namespace
