'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Assignment3_MVC

    Partial Public Class Apricot
        Public Property Form_ID As Integer
        Public Property Fruit_ID As Integer
        Public Property Form As String
        Public Property Average_Retail_Price_Dollars As Nullable(Of Decimal)
        Public Property Price_Unit As String
        Public Property Preparation_yield_Factor As Nullable(Of Decimal)
        Public Property Size_Cup_Equivalent As Nullable(Of Decimal)
        Public Property Size_Unit As String
        Public Property Average_Price_Per_Cup_Dollars As Nullable(Of Decimal)
    
        Public Overridable Property Fruit As Fruit
    
    End Class

End Namespace
