'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Assignment3_MVC

    Partial Public Class Vegetable
        Public Property Veg_ID As Integer
        Public Property Product_ID As Integer
        Public Property Veg_Name As String
    
        Public Overridable Property Agri_Products As Agri_Products
        Public Overridable Property Mushrooms As ICollection(Of Mushroom) = New HashSet(Of Mushroom)
        Public Overridable Property Potatoes As ICollection(Of Potato) = New HashSet(Of Potato)
        Public Overridable Property Tomatoes As ICollection(Of Tomato) = New HashSet(Of Tomato)
    
    End Class

End Namespace
